steps:
- name: 'python:3.7'
  args: ['pip3','install', '-r', 'requirements.txt', '-r', 'requiements-test.txt', '--user']
- name: 'python:3.7'
  args: ['python3','-m', 'unittest']
- name: 'python:3.7'
  args: ['./pytype_script.sh']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/filter-feed:$COMMIT_SHA', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/filter-feed:$COMMIT_SHA']
- name: 'gcr.io/cloud-builders/gcloud'
  args: 
  - 'run'
  - 'deploy'
  - 'filter-feed'
  - '--image'
  - 'gcr.io/$PROJECT_ID/filter-feed:$COMMIT_SHA'
  - '--region'
  - 'us-central1'
  - '--platform'
  - 'managed'
  - '--allow-unauthenticated'
images:
- 'gcr.io/$PROJECT_ID/filter-feed:$COMMIT_SHA'
